version: "3.7"
services:
  unifi-network-controller:
    image: peterpakos/unifi-network-controller
    ports:
      - 3478:3478/udp
      - 6789:6789
      - 8080:8080
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 10001:10001/udp
    volumes:
      - ./data:/UniFi/data
    restart: unless-stopped
